spring:
  output:
    ansi:
      enabled: ALWAYS
      datasource:
        url: jdbc:h2:file:${user.home}/kotlin-njagi/db
        username: sa
        password: sa
      Jpa:
        hibernate:
          ddl-auto: update


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
